# Site settings
title: Mallorcaultracycling
email: info@mallorcaultracycling.com
description: > # this means to ignore newlines until "baseurl:"
  Ciclistas de Ultra fondo de Mallorca informarán de su trabajo,
  sus proyectos y todo lo relacionado con esta modalidad de ciclismo.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mallorcaultracycling.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  mallorcaultracycling

# Build settings
markdown: kramdown
